import { useEffect, useRef, useState } from 'react';
import { supabase } from '../supabase';
import BarcodeScanner from 'react-qr-barcode-scanner';
import {
  QrCode, History, Shield, CheckCircle, XCircle, Clock,
  User, Search, ArrowLeft, AlertCircle, Scan
} from 'lucide-react';

// Matches the QR payload the Parent portal encodes (see ParentPortal.tsx PickupQRPayload) —
// the guardian name, guardian relationship, and student name, plus the IDs needed to verify
// those names actually correspond to a real, currently-linked/authorized record.
type PickupQRPayload =
  | { type: 'permanent'; guardianId: string; guardianName: string; relationship: string; studentId: string; studentName: string }
  | { type: 'temporary'; authId: string; guardianName: string; relationship: string; studentId: string; studentName: string };

function parsePickupQRPayload(text: string): PickupQRPayload | null {
  try {
    const data = JSON.parse(text);
    if (data && (data.type === 'permanent' || data.type === 'temporary') && data.studentId && data.guardianName && data.relationship) {
      return data as PickupQRPayload;
    }
  } catch {
    // Not a QR code generated by this system.
  }
  return null;
}

interface GuardPortalProps {
  user: any;
  onLogout: () => void;
}

interface PickupRecord {
  id: string;
  studentName: string;
  studentId: string;
  studentGrade: string;
  parentName: string;
  parentId: string;
  timestamp: Date;
  status: 'completed' | 'pending';
  guardName: string;
}

export function GuardPortal({ user, onLogout }: GuardPortalProps) {
  const [activeView, setActiveView] = useState<'home' | 'scan' | 'history'>('home');
  const [scanning, setScanning] = useState(false);
  const [validating, setValidating] = useState(false);
  const [scanResult, setScanResult] = useState<PickupRecord | null>(null);
  const [pickupHistory, setPickupHistory] = useState<PickupRecord[]>([]);
  const [searchQuery, setSearchQuery] = useState('');
  const [currentTime, setCurrentTime] = useState(new Date());
  const [historyLoading, setHistoryLoading] = useState(true);
  const [scanError, setScanError] = useState<string | null>(null);
  const [schoolYearId, setSchoolYearId] = useState<string | null>(null);
  // Guards against the scanner firing onUpdate again for the same code while a
  // previous decode is still being validated/recorded.
  const processingRef = useRef(false);

  // Update time every second
  useEffect(() => {
    const timer = setInterval(() => setCurrentTime(new Date()), 1000);
    return () => clearInterval(timer);
  }, []);

  const loadPickupHistory = async () => {
    setHistoryLoading(true);
    const { data, error } = await supabase
      .from('pickup_logs')
      .select(`
        id,
        student_id,
        guardian_id,
        picked_up_by_name,
        relationship,
        scanned_at,
        students ( first_name, last_name, grade_level ),
        guardians ( full_name )
      `)
      .order('scanned_at', { ascending: false })
      .limit(100);

    if (!error && data) {
      const records: PickupRecord[] = data.map((row: any) => {
        const student = row.students;
        const guardian = row.guardians;
        return {
          id: row.id,
          studentName: student ? `${student.first_name} ${student.last_name}` : row.student_id,
          studentId: row.student_id,
          studentGrade: student?.grade_level ?? '—',
          parentName: guardian?.full_name ?? row.picked_up_by_name ?? 'Unknown',
          parentId: row.guardian_id ?? (row.relationship ? row.relationship : '—'),
          timestamp: new Date(row.scanned_at),
          status: 'completed',
          guardName: user.name,
        };
      });
      setPickupHistory(records);
    }
    setHistoryLoading(false);
  };

  // Load real pickup history from Supabase
  useEffect(() => {
    loadPickupHistory();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // Load the current school year, for recording new pickups against it.
  useEffect(() => {
    (async () => {
      const { data: sy } = await supabase
        .from('school_years')
        .select('id')
        .eq('is_current', true)
        .limit(1)
        .maybeSingle();
      if (sy) setSchoolYearId(sy.id);
    })();
  }, []);

  const startScanning = () => {
    setScanError(null);
    setScanResult(null);
    processingRef.current = false;
    setScanning(true);
  };

  const stopScanning = () => {
    setScanning(false);
    setValidating(false);
    processingRef.current = false;
  };

  // Called on every camera frame; `result` is only set when a code was actually decoded.
  const handleDecode = async (_err: unknown, result?: { getText(): string }) => {
    if (!result || processingRef.current) return;
    const payload = parsePickupQRPayload(result.getText());
    if (!payload) {
      setScanError('This QR code is not a valid pickup code for this system. Please scan again.');
      return;
    }

    processingRef.current = true;
    setValidating(true);
    setScanError(null);

    try {
      const { data: student } = await supabase
        .from('students')
        .select('id, first_name, last_name, grade_level')
        .eq('id', payload.studentId)
        .eq('status', 'Active')
        .maybeSingle();

      if (!student) {
        setScanError('Invalid QR code: this student was not found in the system. Please scan again.');
        return;
      }

      let verifiedGuardianName = payload.guardianName;
      let method: 'qr_persistent' | 'qr_authorization';
      let guardianIdForLog: string | null = null;
      let pickupAuthorizationId: string | null = null;

      if (payload.type === 'permanent') {
        const { data: link } = await supabase
          .from('student_guardians')
          .select('guardian_id, relationship, guardians(full_name)')
          .eq('student_id', payload.studentId)
          .eq('guardian_id', payload.guardianId)
          .maybeSingle();
        if (!link) {
          setScanError('Invalid QR code: this guardian is not on file for this student. Please scan again.');
          return;
        }
        verifiedGuardianName = (link as any).guardians?.full_name ?? payload.guardianName;
        method = 'qr_persistent';
        guardianIdForLog = payload.guardianId;
      } else {
        const { data: auth } = await supabase
          .from('pickup_authorizations')
          .select('id, guardian_name, relationship, valid_until, status')
          .eq('id', payload.authId)
          .eq('student_id', payload.studentId)
          .maybeSingle();
        if (!auth || auth.status !== 'active') {
          setScanError('Invalid QR code: this temporary authorization was not found or has been revoked. Please scan again.');
          return;
        }
        if (new Date(auth.valid_until) < new Date()) {
          setScanError('This temporary QR code has expired. Please scan again or ask the parent for a new one.');
          return;
        }
        verifiedGuardianName = auth.guardian_name;
        method = 'qr_authorization';
        pickupAuthorizationId = auth.id;
      }

      const { data, error } = await supabase
        .from('pickup_logs')
        .insert({
          student_id: student.id,
          school_year_id: schoolYearId,
          method,
          guardian_id: guardianIdForLog,
          pickup_authorization_id: pickupAuthorizationId,
          picked_up_by_name: verifiedGuardianName,
          relationship: payload.relationship,
          scanned_by: user.employeeId ?? null,
          notes: null,
        })
        .select('id, scanned_at')
        .single();

      if (error || !data) {
        setScanError(error?.message ?? 'Could not record this pickup. Please try again.');
        return;
      }

      const newPickup: PickupRecord = {
        id: data.id,
        studentName: `${student.first_name} ${student.last_name}`,
        studentId: student.id,
        studentGrade: student.grade_level,
        parentName: verifiedGuardianName,
        parentId: payload.relationship,
        timestamp: new Date(data.scanned_at),
        status: 'completed',
        guardName: user.name,
      };

      setScanResult(newPickup);
      setPickupHistory(prev => [newPickup, ...prev]);
      setScanning(false);
    } finally {
      setValidating(false);
      processingRef.current = false;
    }
  };

  const confirmPickup = () => {
    setScanResult(null);
    setActiveView('home');
  };

  const filteredHistory = pickupHistory.filter(record => 
    record.studentName.toLowerCase().includes(searchQuery.toLowerCase()) ||
    record.parentName.toLowerCase().includes(searchQuery.toLowerCase()) ||
    record.studentId.toLowerCase().includes(searchQuery.toLowerCase())
  );

  const todayPickups = pickupHistory.filter(record => {
    const today = new Date();
    const recordDate = new Date(record.timestamp);
    return recordDate.toDateString() === today.toDateString();
  });

  return (
    <div className="min-h-screen bg-gradient-to-br from-[#1a2b4a] via-[#2d4263] to-[#1a2b4a] flex items-center justify-center sm:p-4">
      {/* App container: fills the real viewport on phones; on wider screens it's a centered "phone" card */}
      <div className="w-full h-screen sm:h-auto sm:max-w-md bg-white sm:rounded-3xl sm:shadow-2xl overflow-hidden flex flex-col sm:max-h-[90vh]">

        {/* Header */}
        <div className="shrink-0 bg-gradient-to-r from-[#1a2b4a] to-[#7d1935] p-6 text-white relative overflow-hidden">
          {/* Decorative elements */}
          <div className="absolute top-0 right-0 w-32 h-32 bg-[#c9a961] rounded-full opacity-10 blur-2xl"></div>
          <div className="absolute bottom-0 left-0 w-24 h-24 bg-white rounded-full opacity-5 blur-xl"></div>
          
          <div className="relative z-10">
            <div className="flex items-center justify-between mb-6">
              <div className="flex items-center gap-3">
                <div className="w-12 h-12 bg-white/20 backdrop-blur-lg rounded-2xl flex items-center justify-center">
                  <Shield className="w-6 h-6 text-[#c9a961]" />
                </div>
                <div>
                  <div className="text-xs text-white/70 uppercase tracking-wider">Security Portal</div>
                  <div className="font-bold text-lg">{user.name}</div>
                </div>
              </div>
              <button
                onClick={onLogout}
                className="px-4 py-2 bg-white/10 backdrop-blur-lg rounded-xl text-xs font-medium hover:bg-white/20 transition-all"
              >
                Logout
              </button>
            </div>

            {/* Time Display */}
            <div className="bg-white/10 backdrop-blur-lg rounded-2xl p-4">
              <div className="flex items-center justify-between">
                <div>
                  <div className="text-xs text-white/70 mb-1">Current Time</div>
                  <div className="text-2xl font-bold">
                    {currentTime.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' })}
                  </div>
                </div>
                <div className="text-right">
                  <div className="text-xs text-white/70 mb-1">Today</div>
                  <div className="text-sm font-medium">
                    {currentTime.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Content */}
        <div className="flex-1 min-h-0 overflow-y-auto">
          {activeView === 'home' && (
            <div className="p-6 space-y-6">
              {/* Stats */}
              <div className="grid grid-cols-2 gap-4">
                <div className="bg-gradient-to-br from-[#1a2b4a] to-[#2d4263] rounded-2xl p-4 text-white">
                  <CheckCircle className="w-8 h-8 mb-2 text-[#c9a961]" />
                  <div className="text-2xl font-bold">{todayPickups.length}</div>
                  <div className="text-xs text-white/70">Pickups Today</div>
                </div>
                <div className="bg-gradient-to-br from-[#7d1935] to-[#9b2847] rounded-2xl p-4 text-white">
                  <Clock className="w-8 h-8 mb-2 text-[#c9a961]" />
                  <div className="text-2xl font-bold">{pickupHistory.length}</div>
                  <div className="text-xs text-white/70">Total Records</div>
                </div>
              </div>

              {/* Main Actions */}
              <div className="space-y-4">
                <button
                  onClick={() => setActiveView('scan')}
                  className="w-full bg-gradient-to-r from-[#c9a961] to-[#d4af37] text-white p-6 rounded-2xl shadow-lg hover:shadow-xl transition-all group"
                >
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-4">
                      <div className="w-16 h-16 bg-white/20 backdrop-blur-lg rounded-2xl flex items-center justify-center group-hover:scale-110 transition-transform">
                        <QrCode className="w-8 h-8" />
                      </div>
                      <div className="text-left">
                        <div className="text-xl font-bold mb-1">Scan QR Code</div>
                        <div className="text-sm text-white/80">Verify parent pickup</div>
                      </div>
                    </div>
                    <Scan className="w-6 h-6 opacity-50" />
                  </div>
                </button>

                <button
                  onClick={() => setActiveView('history')}
                  className="w-full bg-gradient-to-r from-[#1a2b4a] to-[#2d4263] text-white p-6 rounded-2xl shadow-lg hover:shadow-xl transition-all group"
                >
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-4">
                      <div className="w-16 h-16 bg-white/20 backdrop-blur-lg rounded-2xl flex items-center justify-center group-hover:scale-110 transition-transform">
                        <History className="w-8 h-8" />
                      </div>
                      <div className="text-left">
                        <div className="text-xl font-bold mb-1">View History</div>
                        <div className="text-sm text-white/80">Pickup records log</div>
                      </div>
                    </div>
                    <History className="w-6 h-6 opacity-50" />
                  </div>
                </button>
              </div>

              {/* Recent Pickups */}
              <div>
                <div className="flex items-center justify-between mb-4">
                  <h3 className="font-bold text-[#1a2b4a]">Recent Pickups</h3>
                  <span className="text-xs text-[#6b6456]">{todayPickups.length} today</span>
                </div>
                <div className="space-y-2">
                  {todayPickups.slice(0, 3).map((record) => (
                    <div 
                      key={record.id}
                      className="bg-[#faf8f5] rounded-xl p-4 border border-[#eae7e0]"
                    >
                      <div className="flex items-start justify-between">
                        <div className="flex-1">
                          <div className="font-semibold text-[#1a2b4a] mb-1">
                            {record.studentName}
                          </div>
                          <div className="text-xs text-[#6b6456] space-y-0.5">
                            <div>Parent: {record.parentName}</div>
                            <div>Time: {new Date(record.timestamp).toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' })}</div>
                          </div>
                        </div>
                        <div className="flex items-center gap-1 text-green-600">
                          <CheckCircle className="w-4 h-4" />
                          <span className="text-xs font-medium">Completed</span>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          )}

          {activeView === 'scan' && (
            <div className="p-6 space-y-6">
              <div className="flex items-center gap-3 mb-4">
                <button
                  onClick={() => {
                    setActiveView('home');
                    setScanResult(null);
                    stopScanning();
                  }}
                  className="w-11 h-11 bg-[#faf8f5] rounded-xl flex items-center justify-center hover:bg-[#eae7e0] transition-colors"
                >
                  <ArrowLeft className="w-5 h-5 text-[#1a2b4a]" />
                </button>
                <h2 className="text-xl font-bold text-[#1a2b4a]">Scan QR Code</h2>
              </div>

              {!scanning && !scanResult && (
                <div className="space-y-6">
                  {scanError && (
                    <div className="bg-red-50 border border-red-200 rounded-2xl p-4 flex items-center gap-3">
                      <XCircle className="w-5 h-5 text-red-500 flex-shrink-0" />
                      <span className="text-sm text-red-700">{scanError}</span>
                    </div>
                  )}
                  {/* Scanner Frame */}
                  <div className="relative aspect-square bg-gradient-to-br from-[#1a2b4a] to-[#2d4263] rounded-3xl overflow-hidden">
                    <div className="absolute inset-0 flex items-center justify-center">
                      <div className="relative w-64 h-64">
                        {/* Corner brackets */}
                        <div className="absolute top-0 left-0 w-16 h-16 border-t-4 border-l-4 border-[#c9a961] rounded-tl-2xl"></div>
                        <div className="absolute top-0 right-0 w-16 h-16 border-t-4 border-r-4 border-[#c9a961] rounded-tr-2xl"></div>
                        <div className="absolute bottom-0 left-0 w-16 h-16 border-b-4 border-l-4 border-[#c9a961] rounded-bl-2xl"></div>
                        <div className="absolute bottom-0 right-0 w-16 h-16 border-b-4 border-r-4 border-[#c9a961] rounded-br-2xl"></div>
                        
                        {/* Center icon */}
                        <div className="absolute inset-0 flex items-center justify-center">
                          <QrCode className="w-24 h-24 text-white/30" />
                        </div>
                      </div>
                    </div>
                  </div>

                  {/* Instructions */}
                  <div className="bg-[#faf8f5] rounded-2xl p-6 border border-[#eae7e0]">
                    <div className="flex items-start gap-3">
                      <div className="w-10 h-10 bg-[#c9a961]/10 rounded-xl flex items-center justify-center flex-shrink-0">
                        <AlertCircle className="w-5 h-5 text-[#c9a961]" />
                      </div>
                      <div className="flex-1">
                        <h4 className="font-semibold text-[#1a2b4a] mb-2">Instructions</h4>
                        <ul className="text-sm text-[#6b6456] space-y-2">
                          <li className="flex items-start gap-2">
                            <span className="w-1.5 h-1.5 bg-[#c9a961] rounded-full mt-1.5"></span>
                            <span>Ask the parent to show their QR code</span>
                          </li>
                          <li className="flex items-start gap-2">
                            <span className="w-1.5 h-1.5 bg-[#c9a961] rounded-full mt-1.5"></span>
                            <span>Position the QR code within the frame</span>
                          </li>
                          <li className="flex items-start gap-2">
                            <span className="w-1.5 h-1.5 bg-[#c9a961] rounded-full mt-1.5"></span>
                            <span>Verify student information matches</span>
                          </li>
                          <li className="flex items-start gap-2">
                            <span className="w-1.5 h-1.5 bg-[#c9a961] rounded-full mt-1.5"></span>
                            <span>Confirm pickup completion</span>
                          </li>
                        </ul>
                      </div>
                    </div>
                  </div>

                  {/* Scan Button */}
                  <button
                    onClick={startScanning}
                    className="w-full bg-gradient-to-r from-[#c9a961] to-[#d4af37] text-white py-4 rounded-2xl font-bold text-lg shadow-lg hover:shadow-xl transition-all flex items-center justify-center gap-2"
                  >
                    <Scan className="w-6 h-6" />
                    Start Scanning
                  </button>
                </div>
              )}

              {scanning && (
                <div className="space-y-6">
                  {scanError && (
                    <div className="bg-red-50 border border-red-200 rounded-2xl p-4 flex items-center gap-3">
                      <XCircle className="w-5 h-5 text-red-500 flex-shrink-0" />
                      <span className="text-sm text-red-700">{scanError}</span>
                    </div>
                  )}
                  <div className="relative aspect-square bg-black rounded-3xl overflow-hidden">
                    <div className="absolute inset-0">
                      <BarcodeScanner
                        onUpdate={handleDecode}
                        onError={() => setScanError('Could not access the camera. Please check camera permissions and try again.')}
                        facingMode="environment"
                        delay={400}
                      />
                    </div>
                    <div className="absolute inset-0 flex items-center justify-center pointer-events-none">
                      <div className="relative w-64 h-64">
                        <div className="absolute top-0 left-0 w-16 h-16 border-t-4 border-l-4 border-[#c9a961] rounded-tl-2xl"></div>
                        <div className="absolute top-0 right-0 w-16 h-16 border-t-4 border-r-4 border-[#c9a961] rounded-tr-2xl"></div>
                        <div className="absolute bottom-0 left-0 w-16 h-16 border-b-4 border-l-4 border-[#c9a961] rounded-bl-2xl"></div>
                        <div className="absolute bottom-0 right-0 w-16 h-16 border-b-4 border-r-4 border-[#c9a961] rounded-br-2xl"></div>
                      </div>
                    </div>
                  </div>

                  <div className="text-center">
                    <div className="inline-flex items-center gap-2 bg-[#c9a961]/10 px-6 py-3 rounded-full">
                      <div className="w-2 h-2 bg-[#c9a961] rounded-full animate-pulse"></div>
                      <span className="text-[#1a2b4a] font-medium">{validating ? 'Verifying…' : 'Point the camera at the QR code'}</span>
                    </div>
                  </div>

                  <button
                    onClick={stopScanning}
                    className="w-full bg-[#faf8f5] text-[#1a2b4a] py-3 rounded-2xl font-semibold border-2 border-[#eae7e0] hover:bg-[#eae7e0] transition-all"
                  >
                    Cancel
                  </button>
                </div>
              )}

              {scanResult && (
                <div className="space-y-6">
                  {/* Success Icon */}
                  <div className="flex justify-center">
                    <div className="w-20 h-20 bg-gradient-to-br from-green-500 to-green-600 rounded-full flex items-center justify-center shadow-lg">
                      <CheckCircle className="w-12 h-12 text-white" />
                    </div>
                  </div>

                  <div className="text-center">
                    <h3 className="text-2xl font-bold text-[#1a2b4a] mb-2">Scan Successful!</h3>
                    <p className="text-[#6b6456]">Verify the details below</p>
                  </div>

                  {/* Pickup Details */}
                  <div className="bg-[#faf8f5] rounded-2xl p-6 border border-[#eae7e0] space-y-4">
                    <div>
                      <div className="text-xs text-[#6b6456] mb-1">Student Name</div>
                      <div className="text-lg font-bold text-[#1a2b4a]">{scanResult.studentName}</div>
                    </div>
                    <div className="grid grid-cols-2 gap-4">
                      <div>
                        <div className="text-xs text-[#6b6456] mb-1">Student ID</div>
                        <div className="font-semibold text-[#1a2b4a]">{scanResult.studentId}</div>
                      </div>
                      <div>
                        <div className="text-xs text-[#6b6456] mb-1">Grade</div>
                        <div className="font-semibold text-[#1a2b4a]">{scanResult.studentGrade}</div>
                      </div>
                    </div>
                    <div className="pt-4 border-t border-[#eae7e0]">
                      <div className="text-xs text-[#6b6456] mb-1">Parent/Guardian</div>
                      <div className="text-lg font-bold text-[#7d1935]">{scanResult.parentName}</div>
                    </div>
                    <div>
                      <div className="text-xs text-[#6b6456] mb-1">Parent ID</div>
                      <div className="font-semibold text-[#1a2b4a]">{scanResult.parentId}</div>
                    </div>
                    <div>
                      <div className="text-xs text-[#6b6456] mb-1">Pickup Time</div>
                      <div className="font-semibold text-[#1a2b4a]">
                        {new Date(scanResult.timestamp).toLocaleString('en-US', { 
                          hour: '2-digit', 
                          minute: '2-digit',
                          month: 'short',
                          day: 'numeric',
                          year: 'numeric'
                        })}
                      </div>
                    </div>
                  </div>

                  {/* Confirm Button */}
                  <button
                    onClick={confirmPickup}
                    className="w-full bg-gradient-to-r from-green-500 to-green-600 text-white py-4 rounded-2xl font-bold text-lg shadow-lg hover:shadow-xl transition-all"
                  >
                    Confirm Pickup
                  </button>

                  <button
                    onClick={() => setScanResult(null)}
                    className="w-full bg-[#faf8f5] text-[#1a2b4a] py-4 rounded-2xl font-semibold border-2 border-[#eae7e0] hover:bg-[#eae7e0] transition-all"
                  >
                    Scan Again
                  </button>
                </div>
              )}
            </div>
          )}

          {activeView === 'history' && (
            <div className="p-6 space-y-6">
              <div className="flex items-center gap-3 mb-4">
                <button
                  onClick={() => setActiveView('home')}
                  className="w-11 h-11 bg-[#faf8f5] rounded-xl flex items-center justify-center hover:bg-[#eae7e0] transition-colors"
                >
                  <ArrowLeft className="w-5 h-5 text-[#1a2b4a]" />
                </button>
                <h2 className="text-xl font-bold text-[#1a2b4a]">Pickup History</h2>
              </div>

              {/* Search Bar */}
              <div className="relative">
                <Search className="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-[#6b6456]" />
                <input
                  type="text"
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  placeholder="Search by student, parent, or ID..."
                  className="w-full pl-12 pr-4 py-3 bg-[#faf8f5] border-2 border-[#eae7e0] rounded-2xl focus:border-[#c9a961] focus:ring-4 focus:ring-[#c9a961]/10 outline-none transition-all"
                />
              </div>

              {/* Stats */}
              <div className="grid grid-cols-2 gap-3">
                <div className="bg-gradient-to-br from-[#1a2b4a] to-[#2d4263] rounded-xl p-4 text-white">
                  <div className="text-xl font-bold">{todayPickups.length}</div>
                  <div className="text-xs text-white/70">Today</div>
                </div>
                <div className="bg-gradient-to-br from-[#7d1935] to-[#9b2847] rounded-xl p-4 text-white">
                  <div className="text-xl font-bold">{filteredHistory.length}</div>
                  <div className="text-xs text-white/70">Total Found</div>
                </div>
              </div>

              {/* History List */}
              <div className="space-y-3">
                {historyLoading && (
                  <div className="text-center py-12">
                    <p className="text-[#6b6456] font-medium">Loading pickup records…</p>
                  </div>
                )}
                {!historyLoading && filteredHistory.map((record) => {
                  const isToday = new Date(record.timestamp).toDateString() === new Date().toDateString();
                  
                  return (
                    <div 
                      key={record.id}
                      className={`rounded-xl p-4 border-2 transition-all ${
                        isToday 
                          ? 'bg-gradient-to-br from-[#c9a961]/5 to-[#d4af37]/5 border-[#c9a961]/20' 
                          : 'bg-[#faf8f5] border-[#eae7e0]'
                      }`}
                    >
                      <div className="flex items-start justify-between mb-3">
                        <div className="flex-1">
                          <div className="flex items-center gap-2 mb-1">
                            <User className="w-4 h-4 text-[#1a2b4a]" />
                            <span className="font-bold text-[#1a2b4a]">{record.studentName}</span>
                          </div>
                          <div className="text-xs text-[#6b6456]">
                            {record.studentId} • {record.studentGrade}
                          </div>
                        </div>
                        {isToday && (
                          <span className="px-2 py-1 bg-[#c9a961] text-white text-xs font-medium rounded-lg">
                            Today
                          </span>
                        )}
                      </div>

                      <div className="space-y-2 text-sm">
                        <div className="flex items-center gap-2 text-[#6b6456]">
                          <User className="w-3.5 h-3.5" />
                          <span>Parent: {record.parentName}</span>
                        </div>
                        <div className="flex items-center gap-2 text-[#6b6456]">
                          <Clock className="w-3.5 h-3.5" />
                          <span>
                            {new Date(record.timestamp).toLocaleString('en-US', {
                              month: 'short',
                              day: 'numeric',
                              hour: '2-digit',
                              minute: '2-digit'
                            })}
                          </span>
                        </div>
                      </div>

                      <div className="mt-3 pt-3 border-t border-[#eae7e0] flex items-center justify-between">
                        <div className="flex items-center gap-1.5 text-green-600">
                          <CheckCircle className="w-4 h-4" />
                          <span className="text-xs font-medium">Completed</span>
                        </div>
                        <span className="text-xs text-[#6b6456]">ID: {record.id}</span>
                      </div>
                    </div>
                  );
                })}

                {!historyLoading && filteredHistory.length === 0 && (
                  <div className="text-center py-12">
                    <div className="w-16 h-16 bg-[#faf8f5] rounded-full flex items-center justify-center mx-auto mb-4">
                      <History className="w-8 h-8 text-[#6b6456]" />
                    </div>
                    <p className="text-[#6b6456] font-medium">
                      {pickupHistory.length === 0 ? 'No pickups recorded yet' : 'No records found'}
                    </p>
                    <p className="text-sm text-[#8b8476] mt-1">
                      {pickupHistory.length === 0 ? 'Scanned pickups will appear here' : 'Try adjusting your search'}
                    </p>
                  </div>
                )}
              </div>
            </div>
          )}
        </div>
      </div>

      {/* CSS for scanning animation */}
      <style>{`
        @keyframes scan {
          0% { top: 0; }
          50% { top: 100%; }
          100% { top: 0; }
        }
      `}</style>
    </div>
  );
}
